"""add_idempotency_and_webhook_dedup

Revision ID: 99093b58c5cd
Revises: c7d91b4e2a68
Create Date: 2026-08-06 13:09:26.082105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99093b58c5cd'
down_revision: Union[str, Sequence[str], None] = 'c7d91b4e2a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint', 'idempotency_key', name='uq_api_idempotency_user_endpoint_key')
    )
    op.create_index(op.f('ix_api_idempotency_records_created_at'), 'api_idempotency_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_idempotency_records_expires_at'), 'api_idempotency_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_idempotency_records_id'), 'api_idempotency_records', ['id'], unique=False)
    op.create_index(op.f('ix_api_idempotency_records_user_id'), 'api_idempotency_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_content_revisions_id'), 'content_revisions', ['id'], unique=False)
    op.add_column('webhook_logs', sa.Column('delivery_id', sa.String(length=36), nullable=True))
    op.add_column('webhook_logs', sa.Column('dedup_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_webhook_logs_delivery_id'), 'webhook_logs', ['delivery_id'], unique=True)
    op.create_unique_constraint('uq_webhook_log_webhook_dedup', 'webhook_logs', ['webhook_id', 'dedup_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_webhook_log_webhook_dedup', 'webhook_logs', type_='unique')
    op.drop_index(op.f('ix_webhook_logs_delivery_id'), table_name='webhook_logs')
    op.drop_column('webhook_logs', 'dedup_key')
    op.drop_column('webhook_logs', 'delivery_id')
    op.drop_index(op.f('ix_content_revisions_id'), table_name='content_revisions')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_api_idempotency_records_user_id'), table_name='api_idempotency_records')
    op.drop_index(op.f('ix_api_idempotency_records_id'), table_name='api_idempotency_records')
    op.drop_index(op.f('ix_api_idempotency_records_expires_at'), table_name='api_idempotency_records')
    op.drop_index(op.f('ix_api_idempotency_records_created_at'), table_name='api_idempotency_records')
    op.drop_table('api_idempotency_records')
    # ### end Alembic commands ###
