"""Add editorial lifecycle fields

Revision ID: a3a214d9ba6c
Revises: ca9322adfa0e
Create Date: 2026-08-03 19:28:08.532094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a214d9ba6c'
down_revision: Union[str, Sequence[str], None] = 'ca9322adfa0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('blogs', sa.Column('status_changed_by_id', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('status_change_reason', sa.Text(), nullable=True))
    op.add_column('case_studies', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('case_studies', sa.Column('status_changed_by_id', sa.Integer(), nullable=True))
    op.add_column('case_studies', sa.Column('status_change_reason', sa.Text(), nullable=True))
    op.add_column('insights', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('insights', sa.Column('status_changed_by_id', sa.Integer(), nullable=True))
    op.add_column('insights', sa.Column('status_change_reason', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news', sa.Column('status_changed_by_id', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('status_change_reason', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('status_changed_by_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('status_change_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status_change_reason')
    op.drop_column('projects', 'status_changed_by_id')
    op.drop_column('projects', 'status_changed_at')
    op.drop_column('news', 'status_change_reason')
    op.drop_column('news', 'status_changed_by_id')
    op.drop_column('news', 'status_changed_at')
    op.drop_column('insights', 'status_change_reason')
    op.drop_column('insights', 'status_changed_by_id')
    op.drop_column('insights', 'status_changed_at')
    op.drop_column('case_studies', 'status_change_reason')
    op.drop_column('case_studies', 'status_changed_by_id')
    op.drop_column('case_studies', 'status_changed_at')
    op.drop_column('blogs', 'status_change_reason')
    op.drop_column('blogs', 'status_changed_by_id')
    op.drop_column('blogs', 'status_changed_at')
    # ### end Alembic commands ###
