"""Make webhook_id nullable in logs

Revision ID: be751061f90b
Revises: e4828ea52d68
Create Date: 2026-08-13 20:31:24.805777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be751061f90b'
down_revision: Union[str, Sequence[str], None] = 'e4828ea52d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_logs', 'webhook_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('webhook_logs_webhook_id_fkey'), 'webhook_logs', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_logs', 'webhooks', ['webhook_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_logs', type_='foreignkey')
    op.create_foreign_key(op.f('webhook_logs_webhook_id_fkey'), 'webhook_logs', 'webhooks', ['webhook_id'], ['id'], ondelete='CASCADE')
    op.alter_column('webhook_logs', 'webhook_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
