"""recreate webhooks

Revision ID: ca9322adfa0e
Revises: dca1820baa27
Create Date: 2026-07-24 16:56:44.923217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca9322adfa0e'
down_revision: Union[str, Sequence[str], None] = 'dca1820baa27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'content_types')
    op.add_column('webhooks', sa.Column('content_types', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.alter_column('webhooks', 'content_types', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('webhooks', 'content_types',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.JSON(),
               postgresql_using='to_json(content_types)')
