"""Add ai_generated to ContentMixin

Revision ID: d9fcf9f0caf7
Revises: 99093b58c5cd
Create Date: 2026-08-12 23:16:03.284844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fcf9f0caf7'
down_revision: Union[str, Sequence[str], None] = '99093b58c5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('case_studies', sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('insights', sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('news', sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'ai_generated')
    op.drop_column('news', 'ai_generated')
    op.drop_column('insights', 'ai_generated')
    op.drop_column('case_studies', 'ai_generated')
    op.drop_column('blogs', 'ai_generated')
    # ### end Alembic commands ###
