"""Add scheduling and webhook logs fields

Revision ID: e4828ea52d68
Revises: d9fcf9f0caf7
Create Date: 2026-08-13 18:31:17.757857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4828ea52d68'
down_revision: Union[str, Sequence[str], None] = 'd9fcf9f0caf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_blogs_scheduled_at'), 'blogs', ['scheduled_at'], unique=False)
    op.add_column('case_studies', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_case_studies_scheduled_at'), 'case_studies', ['scheduled_at'], unique=False)
    op.add_column('insights', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_insights_scheduled_at'), 'insights', ['scheduled_at'], unique=False)
    op.add_column('news', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_news_scheduled_at'), 'news', ['scheduled_at'], unique=False)
    op.add_column('projects', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_projects_scheduled_at'), 'projects', ['scheduled_at'], unique=False)
    op.add_column('webhook_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('webhook_logs', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('webhook_logs', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('webhook_logs', sa.Column('resolved_by_id', sa.Integer(), nullable=True))
    op.add_column('webhook_logs', sa.Column('resolution_comment', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'webhook_logs', 'users', ['resolved_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_logs', type_='foreignkey')
    op.drop_column('webhook_logs', 'resolution_comment')
    op.drop_column('webhook_logs', 'resolved_by_id')
    op.drop_column('webhook_logs', 'resolved_at')
    op.drop_column('webhook_logs', 'retry_count')
    op.drop_column('webhook_logs', 'duration_ms')
    op.drop_index(op.f('ix_projects_scheduled_at'), table_name='projects')
    op.drop_column('projects', 'scheduled_at')
    op.drop_index(op.f('ix_news_scheduled_at'), table_name='news')
    op.drop_column('news', 'scheduled_at')
    op.drop_index(op.f('ix_insights_scheduled_at'), table_name='insights')
    op.drop_column('insights', 'scheduled_at')
    op.drop_index(op.f('ix_case_studies_scheduled_at'), table_name='case_studies')
    op.drop_column('case_studies', 'scheduled_at')
    op.drop_index(op.f('ix_blogs_scheduled_at'), table_name='blogs')
    op.drop_column('blogs', 'scheduled_at')
    # ### end Alembic commands ###
